"""Prototype solvers for atomistic WAXS cake-map generation."""

from .anisotropic_born import CartesianSpectralBornReference, UniaxialScalarDispersion
from .anisotropic_green import (
    apply_maxwell_spectral_residue,
    maxwell_resolvent_residue,
    maxwell_spectral_residue,
    maxwell_wave_operator,
    maxwell_wave_operator_derivative,
)
from .exact_harmonic import (
    PreparedExactCoordinateHarmonicPlan,
    exact_coordinate_harmonic_amplitude,
    exact_coordinate_harmonic_amplitude_factorized,
)
from .crystal_lattice import (
    repeated_block_translations,
    translation_lattice_factor,
    translation_lattice_factor_separable,
)
from .vector_born import (
    gayer_5mol_mgo_cln_index,
    linbo3_3m_nonlinear_polarization,
    project_vector_born_field,
    uniaxial_eigenpolarization,
)
from .fullwave_gate import summarize_fullwave_arrays
from .axisymmetric_calibration import (
    AnchoredBSplineCurvatureModel,
    EllipsoidCurvatureModel,
    curvature_loss_and_gradient,
    geometry_identifiability,
    geometry_parameter_jacobian,
)
from .axisymmetric_inverse import (
    ConjugateGradientReconstruction,
    conjugate_gradient_tikhonov,
)
from .axisymmetric_manifold import (
    AxisymmetricManifold,
    parameter_trapezoid_weights,
    prepare_axisymmetric_plan,
    surface_radial_weights,
)
from .axisymmetric_operator import PreparedAxisymmetricOperator, normalized_adjoint_error
from .axisymmetric_pde import AxisymmetricPDEPair
from .axisymmetric_validation import (
    AnisotropicGaussianMixture,
    ComplexErrorMetrics,
    PreparedFinufftAxisymmetricReference,
    binned_structure_sources,
    binned_structure_grid,
    complex_error_metrics,
    direct_axisymmetric_amplitude,
    direct_axisymmetric_adjoint,
    sample_gaussian_mixture_midpoint_grid,
)
from .geometry import ewald_ring
from .histogram import (
    BinnedStructure,
    SparseBinnedStructure,
    cylindrical_flat_indices,
    encode_elements,
    make_cylindrical_histogram,
    make_cylindrical_histogram_from_flat_indices,
    make_cylindrical_histogram_from_indices,
    make_cylindrical_histogram_indexed,
    make_sparse_cylindrical_histogram_from_flat_indices,
)
from .odt_measured_contract import (
    OdtMeasuredData,
    PreparedOperatorDescriptor,
    ValidationReport,
    build_prepared_operator_from_contract,
    load_odt_measured_contract,
    save_odt_measured_contract,
    validate_odt_measured_contract,
)
from .odt_double_manifold import (
    PreparedDoubleManifoldOperator,
    cylindrical_coordinates,
    direct_double_manifold_adjoint,
    direct_double_manifold_forward,
    double_manifold_nodes,
)
from .physical_scaling import PhysicalGrid, choose_physical_grid, water_box_side_nm
from .presets import FAST_PRESET_NAMES, fast_preset_options
from .solvers import (
    KernelInterpolationTable,
    PreparedCakePlan,
    circular_fft_amplitude,
    direct_amplitude,
    estimate_bessel_cutoff,
    hybrid_amplitude,
    jacobi_anger_amplitude,
    nufft_amplitude,
    nufft_amplitude_chunked,
)
from .surface_normal import (
    MeshData,
    SurfaceNormalCylindricalPlan,
    SurfaceNormalMoments,
    SurfaceNormalSources,
    amplitude_from_sources,
    centroid_sources,
    coerce_mesh,
    exact_triangle_amplitude,
    median_line_sources,
    mesh_face_normals,
    mesh_signed_volume,
    mesh_volume_moments,
    moment_expansion_amplitude,
    q_grid_from_cylindrical,
    surface_normal_amplitude_from_sources,
    triangle_h,
)
from .xray_form_factors import xray_f0, xray_f0_form_factors

__all__ = [
    "AnchoredBSplineCurvatureModel",
    "AnisotropicGaussianMixture",
    "AxisymmetricManifold",
    "AxisymmetricPDEPair",
    "BinnedStructure",
    "SparseBinnedStructure",
    "CartesianSpectralBornReference",
    "PreparedExactCoordinateHarmonicPlan",
    "apply_maxwell_spectral_residue",
    "exact_coordinate_harmonic_amplitude",
    "exact_coordinate_harmonic_amplitude_factorized",
    "repeated_block_translations",
    "translation_lattice_factor",
    "translation_lattice_factor_separable",
    "ComplexErrorMetrics",
    "ConjugateGradientReconstruction",
    "EllipsoidCurvatureModel",
    "FAST_PRESET_NAMES",
    "KernelInterpolationTable",
    "MeshData",
    "PhysicalGrid",
    "OdtMeasuredData",
    "PreparedOperatorDescriptor",
    "PreparedAxisymmetricOperator",
    "PreparedFinufftAxisymmetricReference",
    "SurfaceNormalCylindricalPlan",
    "SurfaceNormalMoments",
    "SurfaceNormalSources",
    "UniaxialScalarDispersion",
    "gayer_5mol_mgo_cln_index",
    "linbo3_3m_nonlinear_polarization",
    "maxwell_resolvent_residue",
    "maxwell_spectral_residue",
    "maxwell_wave_operator",
    "maxwell_wave_operator_derivative",
    "project_vector_born_field",
    "uniaxial_eigenpolarization",
    "summarize_fullwave_arrays",
    "ValidationReport",
    "amplitude_from_sources",
    "binned_structure_sources",
    "binned_structure_grid",
    "build_prepared_operator_from_contract",
    "PreparedCakePlan",
    "PreparedDoubleManifoldOperator",
    "choose_physical_grid",
    "circular_fft_amplitude",
    "centroid_sources",
    "coerce_mesh",
    "complex_error_metrics",
    "conjugate_gradient_tikhonov",
    "curvature_loss_and_gradient",
    "cylindrical_flat_indices",
    "cylindrical_coordinates",
    "direct_amplitude",
    "direct_double_manifold_adjoint",
    "direct_double_manifold_forward",
    "direct_axisymmetric_adjoint",
    "direct_axisymmetric_amplitude",
    "encode_elements",
    "estimate_bessel_cutoff",
    "ewald_ring",
    "double_manifold_nodes",
    "exact_triangle_amplitude",
    "fast_preset_options",
    "geometry_identifiability",
    "geometry_parameter_jacobian",
    "hybrid_amplitude",
    "jacobi_anger_amplitude",
    "make_cylindrical_histogram",
    "make_cylindrical_histogram_from_flat_indices",
    "make_cylindrical_histogram_from_indices",
    "make_cylindrical_histogram_indexed",
    "make_sparse_cylindrical_histogram_from_flat_indices",
    "load_odt_measured_contract",
    "median_line_sources",
    "mesh_face_normals",
    "mesh_signed_volume",
    "mesh_volume_moments",
    "moment_expansion_amplitude",
    "nufft_amplitude",
    "nufft_amplitude_chunked",
    "normalized_adjoint_error",
    "parameter_trapezoid_weights",
    "prepare_axisymmetric_plan",
    "q_grid_from_cylindrical",
    "save_odt_measured_contract",
    "sample_gaussian_mixture_midpoint_grid",
    "surface_normal_amplitude_from_sources",
    "surface_radial_weights",
    "triangle_h",
    "validate_odt_measured_contract",
    "water_box_side_nm",
    "xray_f0",
    "xray_f0_form_factors",
]
