"""Prototype solvers for atomistic WAXS cake-map generation."""

from .anisotropic_born import CartesianSpectralBornReference, UniaxialScalarDispersion
from .atomic_orbitals import (
    gaussian_orbital_azimuthal_modes,
    gaussian_orbital_degree,
    gaussian_orbital_density_modes,
    gaussian_orbital_fourier,
    gaussian_orbital_names,
    gaussian_orbital_solid_harmonic,
    gaussian_orbital_values,
    polarized_scattering_amplitude,
    transverse_polarization_basis,
)
from .aidt_acfo import (
    PreparedAidtAcfoOperator,
    aidt_transfer_functions_on_points,
    direct_aidt_adjoint,
    direct_aidt_forward,
    direct_lateral_adjoint,
    direct_lateral_fourier,
)
from .aidt_acfo_torch import TorchPreparedAidtAcfoOperator
from .anisotropic_green import (
    apply_maxwell_spectral_residue,
    maxwell_resolvent_residue,
    maxwell_spectral_residue,
    maxwell_wave_operator,
    maxwell_wave_operator_derivative,
)
from .exact_harmonic import (
    PreparedExactCoordinateHarmonicPlan,
    exact_coordinate_harmonic_amplitude,
    exact_coordinate_harmonic_amplitude_factorized,
)
from .crystal_lattice import (
    repeated_block_translations,
    translation_lattice_factor,
    translation_lattice_factor_separable,
)
from .vector_born import (
    gayer_5mol_mgo_cln_index,
    linbo3_3m_nonlinear_polarization,
    project_vector_born_field,
    uniaxial_eigenpolarization,
)
from .fullwave_gate import summarize_fullwave_arrays
from .axisymmetric_calibration import (
    AnchoredBSplineCurvatureModel,
    EllipsoidCurvatureModel,
    curvature_loss_and_gradient,
    geometry_identifiability,
    geometry_parameter_jacobian,
)
from .axisymmetric_inverse import (
    ConjugateGradientReconstruction,
    PrimalDualTVReconstruction,
    ProjectedGradientReconstruction,
    SquareRootDataWeightOperator,
    SymmetricVolumeOperator,
    accelerated_projected_quadratic,
    conjugate_gradient_tikhonov,
    estimate_stacked_operator_norm,
    estimate_tv_gradient_norm,
    primal_dual_cylindrical_tv,
)
from .axisymmetric_manifold import (
    AxisymmetricManifold,
    parameter_trapezoid_weights,
    prepare_axisymmetric_plan,
    surface_radial_weights,
)
from .axisymmetric_operator import PreparedAxisymmetricOperator, normalized_adjoint_error
from .axisymmetric_pde import AxisymmetricPDEPair
from .axisymmetric_validation import (
    AnisotropicGaussianMixture,
    ComplexErrorMetrics,
    PreparedFinufftAxisymmetricReference,
    binned_structure_sources,
    binned_structure_grid,
    complex_error_metrics,
    direct_axisymmetric_amplitude,
    direct_axisymmetric_adjoint,
    sample_gaussian_mixture_midpoint_grid,
)
from .geometry import ewald_ring
from .histogram import (
    BinnedStructure,
    SparseBinnedStructure,
    cylindrical_flat_indices,
    encode_elements,
    make_cylindrical_histogram,
    make_cylindrical_histogram_from_flat_indices,
    make_cylindrical_histogram_from_indices,
    make_cylindrical_histogram_indexed,
    make_sparse_cylindrical_histogram_from_flat_indices,
)
from .harmonic_cutoff import (
    PreparedCutoffAxisymmetricOperator,
    QrHarmonicCutoffPlan,
    build_qr_harmonic_cutoff_plan,
)
from .harmonic_support import (
    CoupledHarmonicSupportDecision,
    HarmonicSupportDecision,
    harmonic_tail_fraction,
    minimum_symmetric_cutoff,
    nested_cutoff_diagnostic,
    resolve_coupled_harmonic_cutoff,
    resolve_source_aware_cutoff,
    signed_angular_modes,
)
from .odt_measured_contract import (
    OdtMeasuredData,
    PreparedOperatorDescriptor,
    ValidationReport,
    build_prepared_operator_from_contract,
    load_odt_measured_contract,
    save_odt_measured_contract,
    validate_odt_measured_contract,
)
from .odt_fourier_diffraction import (
    rytov_fft_to_object_fourier_samples,
    scattering_potential_to_refractive_index,
)
from .odt_double_manifold import (
    PreparedDoubleManifoldOperator,
    PreparedSelectedModeDoubleManifoldOperator,
    cylindrical_coordinates,
    direct_double_manifold_adjoint,
    direct_double_manifold_forward,
    double_manifold_nodes,
)
from .physical_scaling import PhysicalGrid, choose_physical_grid, water_box_side_nm
from .presets import FAST_PRESET_NAMES, fast_preset_options
from .solvers import (
    KernelInterpolationTable,
    PreparedCakePlan,
    circular_fft_amplitude,
    direct_amplitude,
    estimate_bessel_cutoff,
    hybrid_amplitude,
    jacobi_anger_amplitude,
    nufft_amplitude,
    nufft_amplitude_chunked,
)
from .surface_normal import (
    MeshData,
    SurfaceNormalCylindricalPlan,
    SurfaceNormalMoments,
    SurfaceNormalSources,
    amplitude_from_sources,
    centroid_sources,
    coerce_mesh,
    exact_triangle_amplitude,
    median_line_sources,
    mesh_face_normals,
    mesh_signed_volume,
    mesh_volume_moments,
    moment_expansion_amplitude,
    q_grid_from_cylindrical,
    surface_normal_amplitude_from_sources,
    triangle_h,
)
from .spherical_molecular import (
    PreparedSphericalGauntProduct,
    amplitude_coefficients,
    direct_molecular_amplitude,
    pair_intensity_coefficients,
    spherical_harmonic_indices,
    spherical_harmonic_matrix,
    synthesize_spherical_series,
)
from .spherical_bessel import (
    PreparedFFTLogSphericalBesselTransform,
    PreparedSphericalBesselTransform,
    direct_gaussian_transition_fourier,
    gaussian_transition_amplitude_coefficients,
    gaussian_transition_angular_coefficients,
)
from .numerical_orbitals import (
    TabulatedRadialOrbital,
    axisymmetric_transition_angular_coefficients,
    direct_tabulated_transition_fourier,
    tabulated_transition_amplitude_coefficients,
)
from .aligned_transition import (
    PreparedAlignedTransitionContraction,
    PreparedAxisymmetricLegendreADM,
    PreparedPairIntensityLeastSquares,
    direct_aligned_transition_intensity,
    watson_alignment_moments,
)
from .xray_form_factors import xray_f0, xray_f0_form_factors

__all__ = [
    "AnchoredBSplineCurvatureModel",
    "AnisotropicGaussianMixture",
    "AxisymmetricManifold",
    "AxisymmetricPDEPair",
    "BinnedStructure",
    "SparseBinnedStructure",
    "CartesianSpectralBornReference",
    "PreparedExactCoordinateHarmonicPlan",
    "apply_maxwell_spectral_residue",
    "exact_coordinate_harmonic_amplitude",
    "exact_coordinate_harmonic_amplitude_factorized",
    "repeated_block_translations",
    "translation_lattice_factor",
    "translation_lattice_factor_separable",
    "ComplexErrorMetrics",
    "ConjugateGradientReconstruction",
    "PrimalDualTVReconstruction",
    "ProjectedGradientReconstruction",
    "CoupledHarmonicSupportDecision",
    "EllipsoidCurvatureModel",
    "FAST_PRESET_NAMES",
    "KernelInterpolationTable",
    "HarmonicSupportDecision",
    "MeshData",
    "PhysicalGrid",
    "OdtMeasuredData",
    "PreparedOperatorDescriptor",
    "PreparedAxisymmetricOperator",
    "PreparedCutoffAxisymmetricOperator",
    "PreparedAidtAcfoOperator",
    "PreparedAlignedTransitionContraction",
    "TorchPreparedAidtAcfoOperator",
    "PreparedFinufftAxisymmetricReference",
    "SurfaceNormalCylindricalPlan",
    "SurfaceNormalMoments",
    "SurfaceNormalSources",
    "UniaxialScalarDispersion",
    "gayer_5mol_mgo_cln_index",
    "linbo3_3m_nonlinear_polarization",
    "maxwell_resolvent_residue",
    "maxwell_spectral_residue",
    "maxwell_wave_operator",
    "maxwell_wave_operator_derivative",
    "project_vector_born_field",
    "uniaxial_eigenpolarization",
    "summarize_fullwave_arrays",
    "ValidationReport",
    "amplitude_from_sources",
    "amplitude_coefficients",
    "axisymmetric_transition_angular_coefficients",
    "aidt_transfer_functions_on_points",
    "binned_structure_sources",
    "binned_structure_grid",
    "build_qr_harmonic_cutoff_plan",
    "build_prepared_operator_from_contract",
    "PreparedCakePlan",
    "PreparedDoubleManifoldOperator",
    "PreparedAxisymmetricLegendreADM",
    "PreparedPairIntensityLeastSquares",
    "PreparedFFTLogSphericalBesselTransform",
    "PreparedSelectedModeDoubleManifoldOperator",
    "PreparedSphericalBesselTransform",
    "PreparedSphericalGauntProduct",
    "QrHarmonicCutoffPlan",
    "TabulatedRadialOrbital",
    "choose_physical_grid",
    "circular_fft_amplitude",
    "centroid_sources",
    "coerce_mesh",
    "complex_error_metrics",
    "accelerated_projected_quadratic",
    "conjugate_gradient_tikhonov",
    "estimate_stacked_operator_norm",
    "estimate_tv_gradient_norm",
    "primal_dual_cylindrical_tv",
    "SquareRootDataWeightOperator",
    "SymmetricVolumeOperator",
    "curvature_loss_and_gradient",
    "cylindrical_flat_indices",
    "cylindrical_coordinates",
    "direct_amplitude",
    "direct_aidt_adjoint",
    "direct_aidt_forward",
    "direct_lateral_adjoint",
    "direct_lateral_fourier",
    "direct_double_manifold_adjoint",
    "direct_double_manifold_forward",
    "direct_gaussian_transition_fourier",
    "direct_aligned_transition_intensity",
    "direct_tabulated_transition_fourier",
    "direct_molecular_amplitude",
    "direct_axisymmetric_adjoint",
    "direct_axisymmetric_amplitude",
    "encode_elements",
    "estimate_bessel_cutoff",
    "ewald_ring",
    "double_manifold_nodes",
    "exact_triangle_amplitude",
    "fast_preset_options",
    "geometry_identifiability",
    "geometry_parameter_jacobian",
    "gaussian_orbital_azimuthal_modes",
    "gaussian_orbital_degree",
    "gaussian_orbital_density_modes",
    "gaussian_orbital_fourier",
    "gaussian_orbital_names",
    "gaussian_orbital_solid_harmonic",
    "gaussian_orbital_values",
    "gaussian_transition_amplitude_coefficients",
    "gaussian_transition_angular_coefficients",
    "hybrid_amplitude",
    "harmonic_tail_fraction",
    "jacobi_anger_amplitude",
    "make_cylindrical_histogram",
    "make_cylindrical_histogram_from_flat_indices",
    "make_cylindrical_histogram_from_indices",
    "make_cylindrical_histogram_indexed",
    "make_sparse_cylindrical_histogram_from_flat_indices",
    "load_odt_measured_contract",
    "rytov_fft_to_object_fourier_samples",
    "scattering_potential_to_refractive_index",
    "median_line_sources",
    "mesh_face_normals",
    "mesh_signed_volume",
    "mesh_volume_moments",
    "moment_expansion_amplitude",
    "nufft_amplitude",
    "nufft_amplitude_chunked",
    "normalized_adjoint_error",
    "minimum_symmetric_cutoff",
    "nested_cutoff_diagnostic",
    "parameter_trapezoid_weights",
    "polarized_scattering_amplitude",
    "pair_intensity_coefficients",
    "prepare_axisymmetric_plan",
    "q_grid_from_cylindrical",
    "save_odt_measured_contract",
    "resolve_source_aware_cutoff",
    "resolve_coupled_harmonic_cutoff",
    "sample_gaussian_mixture_midpoint_grid",
    "surface_normal_amplitude_from_sources",
    "surface_radial_weights",
    "spherical_harmonic_indices",
    "spherical_harmonic_matrix",
    "synthesize_spherical_series",
    "tabulated_transition_amplitude_coefficients",
    "transverse_polarization_basis",
    "signed_angular_modes",
    "triangle_h",
    "validate_odt_measured_contract",
    "water_box_side_nm",
    "watson_alignment_moments",
    "xray_f0",
    "xray_f0_form_factors",
]
